//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Tokens = new HashSet<Token>();
            this.BusinessUnits = new HashSet<BusinessUnit>();
            this.PersonInfoes = new HashSet<PersonInfo>();
        }
    
        public System.Guid AccountID { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsCompany { get; set; }
        public Nullable<bool> IsPerson { get; set; }
    
        public virtual ICollection<Token> Tokens { get; set; }
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
        public virtual ICollection<PersonInfo> PersonInfoes { get; set; }
    }
}
