//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        public System.Guid AttendeeID { get; set; }
        public System.DateTime TimeOfChecking { get; set; }
        public string DeviceIdentification { get; set; }
        public Nullable<System.Guid> PersonInfoRefID { get; set; }
        public System.Guid PromotionRefID { get; set; }
    
        public virtual PersonInfo PersonInfo { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
