//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnit
    {
        public BusinessUnit()
        {
            this.BusinessUnitReviews = new HashSet<BusinessUnitReview>();
            this.Promotions = new HashSet<Promotion>();
        }
    
        public System.Guid BusinessUnitID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<System.DateTime> DateOfFoundation { get; set; }
        public System.Guid AccountRefID { get; set; }
        public System.Guid LocationRefID { get; set; }
        public byte[] ProfilePicture { get; set; }
    
        public virtual ICollection<BusinessUnitReview> BusinessUnitReviews { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
        public virtual Account Account { get; set; }
    }
}
