//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.BusinessUnits = new HashSet<BusinessUnit>();
            this.PersonInfoes = new HashSet<PersonInfo>();
        }
    
        public System.Guid LocationID { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string ZIP { get; set; }
        public string Street { get; set; }
        public string StreetNumber { get; set; }
        public decimal Letitude { get; set; }
        public decimal Longitude { get; set; }
    
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
        public virtual ICollection<PersonInfo> PersonInfoes { get; set; }
    }
}
