//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInfo
    {
        public PersonInfo()
        {
            this.Attendees = new HashSet<Attendee>();
            this.BusinessUnitReviews = new HashSet<BusinessUnitReview>();
        }
    
        public System.Guid PersonInfoID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.Guid AccountRefID { get; set; }
        public Nullable<System.Guid> LocationRefID { get; set; }
    
        public virtual ICollection<Attendee> Attendees { get; set; }
        public virtual ICollection<BusinessUnitReview> BusinessUnitReviews { get; set; }
        public virtual Location Location { get; set; }
        public virtual Account Account { get; set; }
    }
}
