//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public Promotion()
        {
            this.Attendees = new HashSet<Attendee>();
            this.BusinessUnits = new HashSet<BusinessUnit>();
        }
    
        public System.Guid PromotionID { get; set; }
        public System.DateTime StartDateAndTime { get; set; }
        public System.DateTime EndDateAndTime { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<Attendee> Attendees { get; set; }
        public virtual ICollection<BusinessUnit> BusinessUnits { get; set; }
    }
}
